routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products', 'ProductController');

Route::get('auth/github', 'Auth\LoginController@redirectToProvider')->name('login.github');
Route::get('auth/github/callback', 'Auth\LoginController@handleProviderCallback');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Entity\Product;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();

        return view('products.index')
            ->with(compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::denies('create', Product::class)) {
            Session::flash('alert-warning', '401 Unauthorized');

            return redirect()->route('products.index');
        }

        return view('products.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Gate::denies('create', Product::class)) {
            Session::flash('alert-warning', '401 Unauthorized');

            return redirect()->route('products.index');
        }

        $data = $request->validate([
            'name' => ['required', 'between:3, 255'],
            'price' => ['required', 'numeric', 'min:0']
        ]);

        $data['user_id'] = auth()->user()->id;
        Product::create($data);

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);

        if (Gate::denies('view', $product)) {
            Session::flash('alert-warning', '401 Unauthorized');

            return redirect()->route('products.index');
        }

        return view('products.show')->with(compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        if (Gate::denies('update', $product))
        {
            Session::flash('alert-warning', '401 Unauthorized');

            return redirect()->route('products.index');
        }

        return view('products.edit')->with(compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);

        if (Gate::denies('update', $product))
        {
            Session::flash('alert-warning', '401 Unauthorized');

            return redirect()->route('products.index');
        }

        $data = $request->validate([
            'name' => ['required', 'between:3, 255'],
            'price' => ['required', 'numeric', 'min:0']
        ]);

        $product->update($data);
        $product->save();

        return redirect()->route('products.show', ['product' => $product]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);

        if ($product) {
            if (Gate::denies('delete', $product)) {
                Session::flash('alert-warning', '401 Unauthorized');

                return redirect()->route('products.index');
            }

            Product::destroy($id);
        }

        return redirect()->route('products.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/products') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="text-center h1">
                @yield('header')
            </div>
            @yield('content')
            </div>
        </main>
    </div>
</body>
</html>

resources/views/products/add.blade.php
@extends('layouts.app')

@section('header', 'Add new product')

@section('content')
    <div class="container">
    <form class="form" id="add" method="post" action="{{ route('products.store') }}">
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input class="form-control" name="name" type="text" placeholder="Name" required>
        </div>

        <div class="form-group">
            <label for="price">Price</label>
            <input class="form-control" name="price" type="number" placeholder="Price" required>
        </div>
        <div class="text-center">
            <button class="btn btn-lg btn-block btn-primary" type="submit">Save</button>
        </div>
    </form>

    <div class="invalid-feedback">
        @foreach($errors->all() as $error)
            <span class="text-danger">{{$error}}</span>
        @endforeach
    </div>
    </div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('header', 'Edit product')

@section('content')
    <div class="container">
        <form class="form" id="edit" method="post" action="{{ route('products.update', ['product' => $product]) }}">
            @csrf
            @method('PATCH')
            <div class="form-group">
                <label for="name">Name</label>
                <input class="form-control" name="name" type="text" placeholder="Enter product name" value="{{ $product->name }}" required>
            </div>

            <div class="form-group">
                <label for="price">Price</label>
                <input class="form-control" name="price" type="number" placeholder="Enter product price" value="{{ $product->price }}" required>
            </div>

            <div class="text-center">
                <button class="btn btn-lg btn-block btn-primary" form="edit" type="submit">Save</button>
                <button type="submit" form="delete" class="btn btn-sm btn-danger">Delete</button>
            </div>

        </form>

        <form class="form" id="delete" method="post" action="{{ route('products.destroy', ['product' => $product]) }}">
            @csrf
            @method('DELETE')
        </form>

        <div class="invalid-feedback">
            @foreach($errors->all() as $error)
                <span class="text-danger">{{$error}}</span>
            @endforeach
        </div>

    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('header', 'Products')

@section('content')
    <div class="col-md-4 h2 text-md-left">
        <a class="btn btn-lg btn-success " href="{{ route('products.create') }}" role="button">Add</a>
    </div>
    @if ($products->isNotEmpty())
    <div class="container">
        @if(Session::has('error'))
            <span class="text-danger"> {{ Session::get('error') }} </span>
        @endif
        <ul class="list-group">
            @foreach($products as $product)
                <li class="list-group-item">
                    <a href="{{ route('products.show', ['product' => $product]) }}">{{ $product->name }}</a>
                    <p>{{ $product->price }}</p>

                @can('update', $product)
                    <p class="list-group-item">
                        <a class="btn btn-sm btn-primary" href="{{ route('products.edit', ['product' => $product]) }}" role="button">Edit</a>
                    </p>
                @endcan

                @can('delete', $product)
                    <span class="list-group-item">
                        <form method="post" action="{{ route('products.destroy', ['product' => $product]) }}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-sm btn-danger" title="Delete" type="submit">Delete</button>
                        </form>
                    </span>
                @endcan
                </li>
            @endforeach
        </ul>

        <div class="invalid-feedback">
            @foreach($errors->all() as $error)
                <span class="text-danger">{{$error}}</span>
            @endforeach
        </div>

    </div>

    @else
        <div class="text-center h1">
            No products to display!
        </div>
    @endif

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('header')
    <div class="text-center h1">
        <a href="{{ route('products.index') }}">
            Back to all products</a>
    </div>
@endsection

@section('content')
    <div class="container">
        <div class="h2 text-md-left">
            Product № {{ $product->id }}
        </div>

        <ul class="list-group">
            @if($product)
                <li class="list-group-item">
                    <p>Name: {{ $product->name }}</p>
                    <p>Price: {{ $product->price }}</p>
                    <p>User: {{ $product->user->name }}</p>
                </li>

                    @can('update', $product)
                        <li class="list-group-item">
                            <a class="btn btn-sm btn-primary" href="{{ route('products.edit', ['product' => $product]) }}" role="button">Edit</a>
                        </li>
                    @endcan

                    @can('delete', $product)
                        <li class="list-group-item">
                            <form method="post" action="{{ route('products.destroy', ['product' => $product]) }}">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-sm btn-danger" title="Delete" type="submit">Delete</button>
                            </form>
                        </li>
                    @endcan

            @endif
        </ul>

        <div class="invalid-feedback">
            @foreach($errors->all() as $error)
                <span class="text-danger">{{$error}}</span>
            @endforeach
        </div>

    </div>
@endsection